Task3
V0D14Ka/MainHospital pull request #4
Opened 2022-10-18 09:39 UTC by V0D14Ka

Task3 pull request

2022-10-18 10:27 UTC, 8Vinso8 requested changes
Есть место для улучшений

2022-10-18 10:27 UTC, 8Vinso8 commented on Domain/Logic/IDoctorRepository.cs
> +        bool IsDoctorExists(string doctorName);
А если доктор попадется с таким же фио? Лучше по id проверять, все-таки все методы и так его получают

2022-10-18 10:27 UTC, 8Vinso8 commented on Domain/Logic/IDoctorRepository.cs
> +    public interface IDoctorRepository : IRepository<Doctor>
Нет получения докторов по специализации в репозитории

2022-10-18 10:27 UTC, 8Vinso8 commented on Domain/Models/Specialization.cs
>          public int SpecID { get; set; }
Все таки лучше просто ID назвать, ведь вызываться будет только в контексте специализации и перепутать постараться надо.
Но это я так

2022-10-18 10:27 UTC, 8Vinso8 commented on Domain/Models/Appointment.cs
> +        public Result IsValid()
А если время начала позже времени окончания? Или они равны?

2022-10-18 10:27 UTC, 8Vinso8 commented on Domain/Models/Doctor.cs
> +        public Doctor(int id, string name, string specialization)
Специальность все-таки должна быть Specialization,а не стринг. Не зря ведь целый файл заводил.

2022-10-18 10:27 UTC, 8Vinso8 commented on Domain/Models/Shedule.cs
> +        public Result IsValid()
Нет проверки что начало раньше конца идет

2022-10-18 10:27 UTC, 8Vinso8 commented on Domain/UseCases/AppointmentService.cs
> +        public Result<Appointment> CreateAppointment(int patientId, int doctorId = -1, string specialization = "-")
Лучше перегрузить метод, чем делать через параметры по умолчанию

2022-10-18 10:27 UTC, 8Vinso8 commented on Domain/UseCases/DoctorService.cs
> +        public Result<Doctor> GetDoctorByID(string id)
Зачем id строкой? Если принимать инт, то проблема пустоты сама отпадет, ведь нельзя пустой инт передать

2022-10-19 04:03 UTC, 8Vinso8 requested changes
Нужно добавить получения списка врачей по специальности в сервис

2022-10-19 04:03 UTC, 8Vinso8 commented on Domain/UseCases/DoctorService.cs
> +
А получение докторов по специальностям забыл

2022-10-19 04:56 UTC, 8Vinso8 requested changes

2022-10-19 04:56 UTC, 8Vinso8 commented on Domain/UseCases/DoctorService.cs
> +            return Result.Ok(_db.GetDoctorsBySpec(spec));
Нет проверки валидности специальности, а так же нет вывода ошибки от бд если она есть

2022-10-19 05:17 UTC, 8Vinso8 approved these changes

2022-10-19 05:28 UTC, Vixorem approved these changes

2022-10-19 08:46 UTC, merged